version: '3'
services:
  web:
    image: nginx:alpine
    volumes: 
      - ./compose/site.conf:/etc/nginx/conf.d/site.conf:ro 
    ports:
      - "8080:8000"
    environment:
      - NGINX_HOST=canchas.local
      - NGINX_PORT=80

  django:
    build:
      context: .
      dockerfile: ./compose/django-dockerfile
    command: >
      sh -c "python /app/manage.py makemigrations &&
             python /app/manage.py migrate &&
             gunicorn canchas.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app

    env_file:
      - ./envs/django
      - ./envs/postgres

    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./envs/postgres

  redis:
      image: redis:latest
      container_name: redis
      ports:
          - "6379:6379"
      volumes:
          - ./redis_data:/data

  celery: 
    build:
      context: .
      dockerfile: ./compose/django-dockerfile
    volumes:
      - ./src:/app

    env_file:
      - ./envs/django
      - ./envs/postgres

    command: 
      sh -c 'celery worker -A canchas.celery -l INFO'
    depends_on:
      - postgres
      - redis
