# Generated by Django 3.1 on 2020-08-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservados',
            new_name='Reservado',
        ),
        migrations.AlterField(
            model_name='horario',
            name='cancha',
            field=models.CharField(choices=[('pasto', 'Cancha de Pasto'), ('baby', 'Cancha de Baby'), ('gym', 'Cancha de gimnasio')], db_index=True, max_length=5),
        ),
    ]
