# Generated by Django 3.1 on 2020-08-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_auto_20200816_0929'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('fecha', 'cancha')},
        ),
    ]
