# Generated by Django 3.1 on 2020-08-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_auto_20200816_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
